version: '3'
services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./users.conf:/etc/sftp/users.conf:ro
      - ./volume/testuser:/home/testuser/upload
      - /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    ports:
      - "2222:22"
